site_title = "Arxiv Daily"
limit_days = 14
cache_url = "https://Furyton.github.io/arxiv-feed/cache.json"

[[sources]]
limit = 50
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 50
category = "cs.IR"
title = "Information Retrieval"

[[sources]]
limit = 50
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 50
category = "stat.ML"
title = "stat Machine Learning"

[[sources]]
limit = 50
category = "stat.CO"
title = "Computation"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
